cash_flow_management/authorization/urls.py
from django.urls import path

from authorization.views import login, registration, logout

app_name = 'authorization'

# Регистрируем отдельные ссылки для приложения регистрации и авторизации.
urlpatterns = [
    path('login/', login, name='login'),
    path('register/', registration, name='register'),
    path('logout/', logout, name='logout'),
]

cash_flow_management/cash_flow_management/urls.py
"""
Основной каталог, где храним ссылки и имена для них.
"""

from django.contrib import admin
from django.urls import path, include
from entries.views import home, form, dictionaries, edit_entry, edit_dictionary_item


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('authorization.urls', namespace='authorization')),
    path('', home, name='home'),
    path('?date_from=&date_to=&status=&type=&category=&subcategory=', home, name='home'),
    path('form/', form, name='form'),
    path('edit/<int:entry_id>/', edit_entry, name='edit_entry'),
    path('dictionaries/', dictionaries, name='dictionaries'),
    path('dictionaries/<str:item_type>/<int:item_id>/', edit_dictionary_item, name='edit_dictionary_item'),
]

cash_flow_management/authorization/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    Кастомная модель пользователя, наследуется от AbstractUser.
    В этой модели мы можем добавлять свои методы или свойства, если они нужны.
    """

    def __str__(self):
        """
        Переопределение метода __str__ для удобства отображения имени пользователя в админ-панели.
        """
        return self.username

cash_flow_management/authorization/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from authorization.models import User


class AuthorizationForm(AuthenticationForm):
    """
    Форма авторизации пользователя.
    Включает поля для ввода имени пользователя и пароля.
    """

    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите имя пользователя'
        })
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        })
    )

    class Meta:
        model = User
        fields = ('username', 'password')


class RegistrationForm(UserCreationForm):
    """
    Форма регистрации нового пользователя.
    Включает поля для ввода имени пользователя и паролей.
    """

    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите имя пользователя'
        })
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        })
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Повторите пароль'
        })
    )

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

cash_flow_management/authorization/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse

from authorization.forms import AuthorizationForm, RegistrationForm
from entries.models import Entry


def login(request):
    """
    View для авторизации пользователя.
    :param request:
    :return:
    """
    # Если был отправлен POST запрос, то оздаем форму с данными из запроса.
    if request.method == 'POST':
        form = AuthorizationForm(data=request.POST)

        # Проводим валидацию данных из формы.
        if form.is_valid():

            # Получаем введенные пользователям данные.
            username = request.POST['username']
            password = request.POST['password']

            # Проводим попытку аутентификации пользователя.
            user = auth.authenticate(username=username, password=password)

            # Если пользователь найден - авторизуем пользователя и перенаправляем на домашнюю страницу.
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('home'))

    # Если был отправлен GET запрос - создаем пустую форму.
    else:
        form = AuthorizationForm()

    context = {'form': form, 'entries': Entry.objects.all()}
    return render(request, 'authorization/login.html', context)


def registration(request):
    """
    View для регистрации нового пользователя
    :param request:
    :return:
    """
    # Если был отправлен POST запрос, то оздаем форму с данными из запроса.
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)

        # Проводим валидацию данных из формы.
        if form.is_valid():
            # Сохраняем данные нового пользователя, отправляем сообщение об успешной регистрации и
            # перенаправляем на страницу входа.
            form.save()
            messages.success(request, 'Регистрация прошла успешно')
            return HttpResponseRedirect(reverse('authorization:login'))

    # Если был отправлен GET запрос - создаем пустую форму.
    else:
        form = RegistrationForm()

    context = {'form': form}
    return render(request, 'authorization/register.html', context)


def logout(request):
    """
    View для выхода пользователя
    :param request:
    :return:
    """
    # Осуществляем logout пользователя и перенаправляем на домашнюю страницу
    auth.logout(request)
    return HttpResponseRedirect(reverse('home'))

cash_flow_management/authorization/templates/authorization/login.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Вход в аккаунт</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    .auth-container {
      max-width: 400px;
      margin: 100px auto;
    }
  </style>
</head>

<body>
  <div class="auth-container">
    <h3 class="text-center mb-4">Вход</h3>

    {% if messages or form.non_field_errors %}
    <div class="alert {% if messages%} alert-success {% else %}  alert-warning {% endif %} alert-dismissible fade show" role="alert" style="margin-top: 50px;">
      {% if messages %}
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      {% else %}
        {{ form.non_field_errors }}
      {% endif %}
    </div>
    {% endif %}


    <form action="{% url 'authorization:login' %}" method="post">
      {% csrf_token %}

      <div class="mb-3">
        <label for="{{ form.username.id_for_label }}" class="form-label">Логин</label>
        {{ form.username }}
      </div>
      <div class="mb-3">
        <label for="{{ form.password.id_for_label }}" class="form-label">Пароль</label>
        {{ form.password }}
      </div>

      <button type="submit" class="btn btn-primary w-100">Войти</button>
    </form>

    <div class="text-center mt-3">
      <a href="{% url 'authorization:register' %}">Зарегистрироваться</a>
    </div>
  </div>
</body>
</html>

cash_flow_management/authorization/templates/authorization/register.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Регистрация</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    .auth-container {
      max-width: 400px;
      margin: 100px auto;
    }
  </style>
</head>

<body>
  <div class="auth-container">
    <h3 class="text-center mb-4">Регистрация</h3>

    {% if form.non_field_errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 50px;">
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <form action="{% url 'authorization:register' %}" method="post">
      {% csrf_token %}

      <div class="mb-3">
        <label for="{{ form.username.id_for_label }}" class="form-label">Логин</label>
        {{ form.username }}
      </div>
      <div class="mb-3">
        <label for="{{ form.password1.id_for_label }}" class="form-label">Пароль</label>
        {{ form.password1 }}
      </div>
      <div class="mb-3">
        <label for="{{ form.password2.id_for_label }}" class="form-label">Повторите пароль</label>
        {{ form.password2 }}
      </div>
      <button type="submit" class="btn btn-primary w-100">Создать аккаунт</button>
    </form>

    <div class="text-center mt-3">
      <a href="{% url 'authorization:login' %}">У меня уже есть аккаунт. Войти</a>
    </div>
  </div>
</body>
</html>